[project]
name = "x-mirror"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Timothee Chauvin", email = "timothee.chauvin28@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fire>=0.7.1",
    "httpx>=0.28.1",
    "orjson>=3.11.9",
    "pydantic>=2.13.4",
]

[project.scripts]
x-mirror = "x_mirror.cli:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-httpx>=0.36.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
